### ISSUE TITLE
Ethernet interface in all-in-one image isn't handled by Parallels 8 for Mac.

### ISSUE THREAD

**Issue by captainpp** [Metaswitch/clearwater-vm-images#4]
I've successfully got the Clearwater All in One image installed using Parallels 8 for Mac.  However, the ethernet interface was a bit screwed up after install, as eth0 didn't work correctly and Ubuntu had created eth1 instead.  While eth1 did work, this was sub-optimal, and the hostname wasn't set up properly so various scripts (the monit ones in particular) were broken.  All this added up to the symptom of trying to add lines using Ellis and getting "server errors" reported.

To fix the ethernet interface to work with Parallels (and hopefully other VMs) requires a change to /etc/udev/rules.d/70-persistent-net.rules.  In this is an entry for eth0 - the MAC address should be replaced with a wildcard this:

```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="*", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
```

**Comment by rkd-msw** [comment]
I don't think we're ever likely to retest with Parallels (and it may not even be a problem with 14.04?), so closing.
