### ISSUE TITLE
Update All in One documentation to cover Parallels for Mac

### ISSUE THREAD

**Issue by captainpp** [Metaswitch/clearwater-vm-images#5]
Would probably be worth updating the AIO documentation to cover Parallels for Mac.  The install isn't totally trivial as Parallels doesn't support importing OVF files.  Steps to get it working:
- Download and install the VMWare OVF conversion tool from: https://my.vmware.com/group/vmware/get-download?downloadGroup=OVF-TOOL-3-0-1
- Convert the OVA file to a VMX using a similar command to this: /Applications/VMware\ OVF\ Tool/ovftool ~/Downloads/cw-aio.ova ~/Downloads/cw-aio.vmx
- I got this output which seemed benign:
   Warning:
    - No manifest entry found for: 'cw-aio-disk1.vmdk'.
   Completed successfully
- This actually put the VMX file here ~/Downloads.vmwarevm/cw-aio.vmx
- Then open up Parallels, and Open a VM from the File menu and select the vmx file you've made.

**Comment by rkd-msw** [comment]
I don't think we're ever likely to retest with Parallels, so closing.
